//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03280.common._2017._07;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PartialCopyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.HashMap;
import java.util.Map;
import org.w3._2001.xmlschema.Adapter1;

/**
 * <p>Java class for UDPPortRange complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="UDPPortRange">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="start" type="{http://uri.etsi.org/03280/common/2017/07}UDPPort"/>
 *         <element name="end" type="{http://uri.etsi.org/03280/common/2017/07}UDPPort"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UDPPortRange", propOrder = { "start", "end" })
public class UDPPortRange implements Copyable, PartialCopyable {

  @XmlElement(required = true, type = String.class)
  @XmlJavaTypeAdapter(Adapter1.class)
  @XmlSchemaType(name = "integer")
  protected Integer start;

  @XmlElement(required = true, type = String.class)
  @XmlJavaTypeAdapter(Adapter1.class)
  @XmlSchemaType(name = "integer")
  protected Integer end;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public UDPPortRange() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a UDPPortRange copying the state of another UDPPortRange
   *
   * @param _other
   *     The original UDPPortRange from which to copy state.
   */
  public UDPPortRange(final UDPPortRange _other) {
    this.start = _other.start;
    this.end = _other.end;
  }

  /**
   * Instantiates a UDPPortRange copying the state of another UDPPortRange
   *
   * @param _other
   *     The original UDPPortRange from which to copy state.
   * @param _propertyTree
   *     A restricting {@link PropertyPath} that defines which nodes of the source object tree should actually be copied.
   * @param _propertyTreeUse
   *     Meaning of the {@link PropertyPath}: Exclude or include members contained in property path.
   */
  public UDPPortRange(
    final UDPPortRange _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final PropertyTree startPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("start"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (startPropertyTree != null)
          : ((startPropertyTree == null) || (!startPropertyTree.isLeaf())))
    ) {
      this.start = _other.start;
    }
    final PropertyTree endPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("end"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (endPropertyTree != null)
          : ((endPropertyTree == null) || (!endPropertyTree.isLeaf())))
    ) {
      this.end = _other.end;
    }
  }

  /**
   * Gets the value of the start property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public Integer getStart() {
    return start;
  }

  /**
   * Sets the value of the start property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setStart(Integer value) {
    this.start = value;
  }

  /**
   * Gets the value of the end property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public Integer getEnd() {
    return end;
  }

  /**
   * Sets the value of the end property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setEnd(Integer value) {
    this.end = value;
  }

  @Override
  public UDPPortRange createCopy() {
    final UDPPortRange _newObject;
    try {
      _newObject = ((UDPPortRange) super.clone());
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
    _newObject.start = this.start;
    _newObject.end = this.end;
    return _newObject;
  }

  @Override
  public UDPPortRange createCopy(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
    final UDPPortRange _newObject;
    try {
      _newObject = ((UDPPortRange) super.clone());
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
    final PropertyTree startPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("start"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (startPropertyTree != null)
          : ((startPropertyTree == null) || (!startPropertyTree.isLeaf())))
    ) {
      _newObject.start = this.start;
    }
    final PropertyTree endPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("end"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (endPropertyTree != null)
          : ((endPropertyTree == null) || (!endPropertyTree.isLeaf())))
    ) {
      _newObject.end = this.end;
    }
    return _newObject;
  }

  @Override
  public UDPPortRange copyExcept(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.EXCLUDE);
  }

  @Override
  public UDPPortRange copyOnly(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.INCLUDE);
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final UDPPortRange.Builder<_B> _other) {
    _other.start = this.start;
    _other.end = this.end;
  }

  public <_B> UDPPortRange.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new UDPPortRange.Builder<_B>(_parentBuilder, this, true);
  }

  public UDPPortRange.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static UDPPortRange.Builder<Void> builder() {
    return new UDPPortRange.Builder<>(null, null, false);
  }

  public static <_B> UDPPortRange.Builder<_B> copyOf(final UDPPortRange _other) {
    final UDPPortRange.Builder<_B> _newBuilder = new UDPPortRange.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final UDPPortRange.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final PropertyTree startPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("start"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (startPropertyTree != null)
          : ((startPropertyTree == null) || (!startPropertyTree.isLeaf())))
    ) {
      _other.start = this.start;
    }
    final PropertyTree endPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("end"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (endPropertyTree != null)
          : ((endPropertyTree == null) || (!endPropertyTree.isLeaf())))
    ) {
      _other.end = this.end;
    }
  }

  public <_B> UDPPortRange.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new UDPPortRange.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  public UDPPortRange.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> UDPPortRange.Builder<_B> copyOf(
    final UDPPortRange _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final UDPPortRange.Builder<_B> _newBuilder = new UDPPortRange.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static UDPPortRange.Builder<Void> copyExcept(final UDPPortRange _other, final PropertyTree _propertyTree) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static UDPPortRange.Builder<Void> copyOnly(final UDPPortRange _other, final PropertyTree _propertyTree) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> implements Buildable {

    protected final _B _parentBuilder;
    protected final UDPPortRange _storedValue;
    private Integer start;
    private Integer end;

    public Builder(final _B _parentBuilder, final UDPPortRange _other, final boolean _copy) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          this.start = _other.start;
          this.end = _other.end;
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public Builder(
      final _B _parentBuilder,
      final UDPPortRange _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          final PropertyTree startPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("start"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (startPropertyTree != null)
                : ((startPropertyTree == null) || (!startPropertyTree.isLeaf())))
          ) {
            this.start = _other.start;
          }
          final PropertyTree endPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("end"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (endPropertyTree != null)
                : ((endPropertyTree == null) || (!endPropertyTree.isLeaf())))
          ) {
            this.end = _other.end;
          }
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public _B end() {
      return this._parentBuilder;
    }

    protected <_P extends UDPPortRange> _P init(final _P _product) {
      _product.start = this.start;
      _product.end = this.end;
      return _product;
    }

    /**
     * Sets the new value of "start" (any previous value will be replaced)
     *
     * @param start
     *     New value of the "start" property.
     */
    public UDPPortRange.Builder<_B> withStart(final Integer start) {
      this.start = start;
      return this;
    }

    /**
     * Sets the new value of "end" (any previous value will be replaced)
     *
     * @param end
     *     New value of the "end" property.
     */
    public UDPPortRange.Builder<_B> withEnd(final Integer end) {
      this.end = end;
      return this;
    }

    @Override
    public UDPPortRange build() {
      if (_storedValue == null) {
        return this.init(new UDPPortRange());
      } else {
        return ((UDPPortRange) _storedValue);
      }
    }

    public UDPPortRange.Builder<_B> copyOf(final UDPPortRange _other) {
      _other.copyTo(this);
      return this;
    }

    public UDPPortRange.Builder<_B> copyOf(final UDPPortRange.Builder _other) {
      return copyOf(_other.build());
    }
  }

  public static class Select extends UDPPortRange.Selector<UDPPortRange.Select, Void> {

    Select() {
      super(null, null, null);
    }

    public static UDPPortRange.Select _root() {
      return new UDPPortRange.Select();
    }
  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
    extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

    private com.kscs.util.jaxb.Selector<TRoot, UDPPortRange.Selector<TRoot, TParent>> start = null;
    private com.kscs.util.jaxb.Selector<TRoot, UDPPortRange.Selector<TRoot, TParent>> end = null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<>();
      products.putAll(super.buildChildren());
      if (this.start != null) {
        products.put("start", this.start.init());
      }
      if (this.end != null) {
        products.put("end", this.end.init());
      }
      return products;
    }

    public com.kscs.util.jaxb.Selector<TRoot, UDPPortRange.Selector<TRoot, TParent>> start() {
      return (
        (this.start == null) ? this.start = new com.kscs.util.jaxb.Selector<>(this._root, this, "start") : this.start
      );
    }

    public com.kscs.util.jaxb.Selector<TRoot, UDPPortRange.Selector<TRoot, TParent>> end() {
      return ((this.end == null) ? this.end = new com.kscs.util.jaxb.Selector<>(this._root, this, "end") : this.end);
    }
  }
}
