//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

/*
 * SPDX-License-Identifier: MIT
 */
package org.etsi.uri._03221.x1._2017._10.hashedid;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for HashAlgorithm.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="HashAlgorithm">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="sha-256"/>
 *     <enumeration value="sha-512"/>
 *     <enumeration value="sha3-512"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 *
 */
@XmlType(name = "HashAlgorithm")
@XmlEnum
public enum HashAlgorithm {
  @XmlEnumValue("sha-256")
  SHA_256("sha-256"),
  @XmlEnumValue("sha-512")
  SHA_512("sha-512"),
  @XmlEnumValue("sha3-512")
  SHA_3_512("sha3-512");

  private final String value;

  HashAlgorithm(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static HashAlgorithm fromValue(String v) {
    for (HashAlgorithm c : HashAlgorithm.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
