//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for CreateDestinationRequest complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="CreateDestinationRequest">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1RequestMessage">
 *       <sequence>
 *         <element name="destinationDetails" type="{http://uri.etsi.org/03221/X1/2017/10}DestinationDetails"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateDestinationRequest", propOrder = { "destinationDetails" })
public class CreateDestinationRequest extends X1RequestMessage implements Copyable {

  @XmlElement(required = true)
  protected DestinationDetails destinationDetails;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public CreateDestinationRequest() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a CreateDestinationRequest copying the state of another CreateDestinationRequest
   *
   * @param _other
   *     The original CreateDestinationRequest from which to copy state.
   */
  public CreateDestinationRequest(final CreateDestinationRequest _other) {
    super(_other);
    this.destinationDetails = ((_other.destinationDetails == null) ? null : _other.destinationDetails.createCopy());
  }

  /**
   * Gets the value of the destinationDetails property.
   *
   * @return
   *     possible object is
   *     {@link DestinationDetails }
   *
   */
  public DestinationDetails getDestinationDetails() {
    return destinationDetails;
  }

  /**
   * Sets the value of the destinationDetails property.
   *
   * @param value
   *     allowed object is
   *     {@link DestinationDetails }
   *
   */
  public void setDestinationDetails(DestinationDetails value) {
    this.destinationDetails = value;
  }

  @Override
  public CreateDestinationRequest createCopy() {
    final CreateDestinationRequest _newObject = ((CreateDestinationRequest) super.createCopy());
    _newObject.destinationDetails = ((this.destinationDetails == null) ? null : this.destinationDetails.createCopy());
    return _newObject;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final CreateDestinationRequest.Builder<_B> _other) {
    super.copyTo(_other);
    _other.destinationDetails = ((this.destinationDetails == null)
        ? null
        : this.destinationDetails.newCopyBuilder(_other));
  }

  @Override
  public <_B> CreateDestinationRequest.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new CreateDestinationRequest.Builder<_B>(_parentBuilder, this, true);
  }

  @Override
  public CreateDestinationRequest.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static CreateDestinationRequest.Builder<Void> builder() {
    return new CreateDestinationRequest.Builder<>(null, null, false);
  }

  public static <_B> CreateDestinationRequest.Builder<_B> copyOf(final X1RequestMessage _other) {
    final CreateDestinationRequest.Builder<_B> _newBuilder = new CreateDestinationRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  public static <_B> CreateDestinationRequest.Builder<_B> copyOf(final CreateDestinationRequest _other) {
    final CreateDestinationRequest.Builder<_B> _newBuilder = new CreateDestinationRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final CreateDestinationRequest.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super.copyTo(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree destinationDetailsPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("destinationDetails"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (destinationDetailsPropertyTree != null)
          : ((destinationDetailsPropertyTree == null) || (!destinationDetailsPropertyTree.isLeaf())))
    ) {
      _other.destinationDetails = ((this.destinationDetails == null)
          ? null
          : this.destinationDetails.newCopyBuilder(_other, destinationDetailsPropertyTree, _propertyTreeUse));
    }
  }

  @Override
  public <_B> CreateDestinationRequest.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new CreateDestinationRequest.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  @Override
  public CreateDestinationRequest.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> CreateDestinationRequest.Builder<_B> copyOf(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final CreateDestinationRequest.Builder<_B> _newBuilder = new CreateDestinationRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static <_B> CreateDestinationRequest.Builder<_B> copyOf(
    final CreateDestinationRequest _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final CreateDestinationRequest.Builder<_B> _newBuilder = new CreateDestinationRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static CreateDestinationRequest.Builder<Void> copyExcept(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static CreateDestinationRequest.Builder<Void> copyExcept(
    final CreateDestinationRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static CreateDestinationRequest.Builder<Void> copyOnly(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static CreateDestinationRequest.Builder<Void> copyOnly(
    final CreateDestinationRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> extends X1RequestMessage.Builder<_B> implements Buildable {

    private DestinationDetails.Builder<CreateDestinationRequest.Builder<_B>> destinationDetails;

    public Builder(final _B _parentBuilder, final CreateDestinationRequest _other, final boolean _copy) {
      super(_parentBuilder, _other, _copy);
      if (_other != null) {
        this.destinationDetails = ((_other.destinationDetails == null)
            ? null
            : _other.destinationDetails.newCopyBuilder(this));
      }
    }

    public Builder(
      final _B _parentBuilder,
      final CreateDestinationRequest _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
      if (_other != null) {
        final PropertyTree destinationDetailsPropertyTree =
          ((_propertyTree == null) ? null : _propertyTree.get("destinationDetails"));
        if (
          ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (destinationDetailsPropertyTree != null)
              : ((destinationDetailsPropertyTree == null) || (!destinationDetailsPropertyTree.isLeaf())))
        ) {
          this.destinationDetails = ((_other.destinationDetails == null)
              ? null
              : _other.destinationDetails.newCopyBuilder(this, destinationDetailsPropertyTree, _propertyTreeUse));
        }
      }
    }

    protected <_P extends CreateDestinationRequest> _P init(final _P _product) {
      _product.destinationDetails = ((this.destinationDetails == null) ? null : this.destinationDetails.build());
      return super.init(_product);
    }

    /**
     * Sets the new value of "destinationDetails" (any previous value will be replaced)
     *
     * @param destinationDetails
     *     New value of the "destinationDetails" property.
     */
    public CreateDestinationRequest.Builder<_B> withDestinationDetails(final DestinationDetails destinationDetails) {
      this.destinationDetails = ((destinationDetails == null)
          ? null
          : new DestinationDetails.Builder<>(this, destinationDetails, false));
      return this;
    }

    /**
     * Returns the existing builder or a new builder to build the value of the
     * "destinationDetails" property.
     * Use {@link org.etsi.uri._03221.x1._2017._10.DestinationDetails.Builder#end()} to
     * return to the current builder.
     *
     * @return
     *     A new builder to build the value of the "destinationDetails" property.
     *     Use {@link org.etsi.uri._03221.x1._2017._10.DestinationDetails.Builder#end()} to
     *     return to the current builder.
     */
    public DestinationDetails.Builder<? extends CreateDestinationRequest.Builder<_B>> withDestinationDetails() {
      if (this.destinationDetails != null) {
        return this.destinationDetails;
      }
      return this.destinationDetails = new DestinationDetails.Builder<>(this, null, false);
    }

    /**
     * Sets the new value of "admfIdentifier" (any previous value will be replaced)
     *
     * @param admfIdentifier
     *     New value of the "admfIdentifier" property.
     */
    @Override
    public CreateDestinationRequest.Builder<_B> withAdmfIdentifier(final String admfIdentifier) {
      super.withAdmfIdentifier(admfIdentifier);
      return this;
    }

    /**
     * Sets the new value of "neIdentifier" (any previous value will be replaced)
     *
     * @param neIdentifier
     *     New value of the "neIdentifier" property.
     */
    @Override
    public CreateDestinationRequest.Builder<_B> withNeIdentifier(final String neIdentifier) {
      super.withNeIdentifier(neIdentifier);
      return this;
    }

    /**
     * Sets the new value of "messageTimestamp" (any previous value will be replaced)
     *
     * @param messageTimestamp
     *     New value of the "messageTimestamp" property.
     */
    @Override
    public CreateDestinationRequest.Builder<_B> withMessageTimestamp(final XMLGregorianCalendar messageTimestamp) {
      super.withMessageTimestamp(messageTimestamp);
      return this;
    }

    /**
     * Sets the new value of "version" (any previous value will be replaced)
     *
     * @param version
     *     New value of the "version" property.
     */
    @Override
    public CreateDestinationRequest.Builder<_B> withVersion(final String version) {
      super.withVersion(version);
      return this;
    }

    /**
     * Sets the new value of "x1TransactionId" (any previous value will be replaced)
     *
     * @param x1TransactionId
     *     New value of the "x1TransactionId" property.
     */
    @Override
    public CreateDestinationRequest.Builder<_B> withX1TransactionId(final String x1TransactionId) {
      super.withX1TransactionId(x1TransactionId);
      return this;
    }

    @Override
    public CreateDestinationRequest build() {
      if (_storedValue == null) {
        return this.init(new CreateDestinationRequest());
      } else {
        return ((CreateDestinationRequest) _storedValue);
      }
    }

    public CreateDestinationRequest.Builder<_B> copyOf(final CreateDestinationRequest _other) {
      _other.copyTo(this);
      return this;
    }

    public CreateDestinationRequest.Builder<_B> copyOf(final CreateDestinationRequest.Builder _other) {
      return copyOf(_other.build());
    }
  }
}
