//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

/*
 * SPDX-License-Identifier: MIT
 */
package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PartialCopyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for CreateObjectRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="CreateObjectRequest">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1RequestMessage">
 *       <sequence>
 *         <element name="createObject" type="{http://uri.etsi.org/03221/X1/2017/10}GenericObject"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateObjectRequest", propOrder = { "createObject" })
public class CreateObjectRequest extends X1RequestMessage implements Copyable, PartialCopyable {

  @XmlElement(required = true)
  protected GenericObject createObject;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public CreateObjectRequest() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a CreateObjectRequest copying the state of another CreateObjectRequest
   *
   * @param _other
   *     The original CreateObjectRequest from which to copy state.
   */
  public CreateObjectRequest(final CreateObjectRequest _other) {
    super(_other);
    this.createObject = ((_other.createObject == null) ? null : _other.createObject.createCopy());
  }

  /**
   * Instantiates a CreateObjectRequest copying the state of another CreateObjectRequest
   *
   * @param _other
   *     The original CreateObjectRequest from which to copy state.
   * @param _propertyTree
   *     A restricting {@link PropertyPath} that defines which nodes of the source object tree should actually be copied.
   * @param _propertyTreeUse
   *     Meaning of the {@link PropertyPath}: Exclude or include members contained in property path.
   */
  public CreateObjectRequest(
    final CreateObjectRequest _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree createObjectPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("createObject"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (createObjectPropertyTree != null)
          : ((createObjectPropertyTree == null) || (!createObjectPropertyTree.isLeaf())))
    ) {
      this.createObject = ((_other.createObject == null)
          ? null
          : _other.createObject.createCopy(createObjectPropertyTree, _propertyTreeUse));
    }
  }

  /**
   * Gets the value of the createObject property.
   *
   * @return
   *     possible object is
   *     {@link GenericObject }
   *
   */
  public GenericObject getCreateObject() {
    return createObject;
  }

  /**
   * Sets the value of the createObject property.
   *
   * @param value
   *     allowed object is
   *     {@link GenericObject }
   *
   */
  public void setCreateObject(GenericObject value) {
    this.createObject = value;
  }

  @Override
  public CreateObjectRequest createCopy() {
    final CreateObjectRequest _newObject = ((CreateObjectRequest) super.createCopy());
    _newObject.createObject = ((this.createObject == null) ? null : this.createObject.createCopy());
    return _newObject;
  }

  @Override
  public CreateObjectRequest createCopy(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
    final CreateObjectRequest _newObject = ((CreateObjectRequest) super.createCopy(_propertyTree, _propertyTreeUse));
    final PropertyTree createObjectPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("createObject"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (createObjectPropertyTree != null)
          : ((createObjectPropertyTree == null) || (!createObjectPropertyTree.isLeaf())))
    ) {
      _newObject.createObject = ((this.createObject == null)
          ? null
          : this.createObject.createCopy(createObjectPropertyTree, _propertyTreeUse));
    }
    return _newObject;
  }

  @Override
  public CreateObjectRequest copyExcept(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.EXCLUDE);
  }

  @Override
  public CreateObjectRequest copyOnly(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.INCLUDE);
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final CreateObjectRequest.Builder<_B> _other) {
    super.copyTo(_other);
    _other.createObject = ((this.createObject == null) ? null : this.createObject.newCopyBuilder(_other));
  }

  @Override
  public <_B> CreateObjectRequest.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new CreateObjectRequest.Builder<_B>(_parentBuilder, this, true);
  }

  @Override
  public CreateObjectRequest.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static CreateObjectRequest.Builder<Void> builder() {
    return new CreateObjectRequest.Builder<>(null, null, false);
  }

  public static <_B> CreateObjectRequest.Builder<_B> copyOf(final X1RequestMessage _other) {
    final CreateObjectRequest.Builder<_B> _newBuilder = new CreateObjectRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  public static <_B> CreateObjectRequest.Builder<_B> copyOf(final CreateObjectRequest _other) {
    final CreateObjectRequest.Builder<_B> _newBuilder = new CreateObjectRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final CreateObjectRequest.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super.copyTo(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree createObjectPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("createObject"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (createObjectPropertyTree != null)
          : ((createObjectPropertyTree == null) || (!createObjectPropertyTree.isLeaf())))
    ) {
      _other.createObject = ((this.createObject == null)
          ? null
          : this.createObject.newCopyBuilder(_other, createObjectPropertyTree, _propertyTreeUse));
    }
  }

  @Override
  public <_B> CreateObjectRequest.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new CreateObjectRequest.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  @Override
  public CreateObjectRequest.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> CreateObjectRequest.Builder<_B> copyOf(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final CreateObjectRequest.Builder<_B> _newBuilder = new CreateObjectRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static <_B> CreateObjectRequest.Builder<_B> copyOf(
    final CreateObjectRequest _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final CreateObjectRequest.Builder<_B> _newBuilder = new CreateObjectRequest.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static CreateObjectRequest.Builder<Void> copyExcept(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static CreateObjectRequest.Builder<Void> copyExcept(
    final CreateObjectRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static CreateObjectRequest.Builder<Void> copyOnly(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static CreateObjectRequest.Builder<Void> copyOnly(
    final CreateObjectRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> extends X1RequestMessage.Builder<_B> implements Buildable {

    private GenericObject.Builder<CreateObjectRequest.Builder<_B>> createObject;

    public Builder(final _B _parentBuilder, final CreateObjectRequest _other, final boolean _copy) {
      super(_parentBuilder, _other, _copy);
      if (_other != null) {
        this.createObject = ((_other.createObject == null) ? null : _other.createObject.newCopyBuilder(this));
      }
    }

    public Builder(
      final _B _parentBuilder,
      final CreateObjectRequest _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
      if (_other != null) {
        final PropertyTree createObjectPropertyTree =
          ((_propertyTree == null) ? null : _propertyTree.get("createObject"));
        if (
          ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (createObjectPropertyTree != null)
              : ((createObjectPropertyTree == null) || (!createObjectPropertyTree.isLeaf())))
        ) {
          this.createObject = ((_other.createObject == null)
              ? null
              : _other.createObject.newCopyBuilder(this, createObjectPropertyTree, _propertyTreeUse));
        }
      }
    }

    protected <_P extends CreateObjectRequest> _P init(final _P _product) {
      _product.createObject = ((this.createObject == null) ? null : this.createObject.build());
      return super.init(_product);
    }

    /**
     * Sets the new value of "createObject" (any previous value will be replaced)
     *
     * @param createObject
     *     New value of the "createObject" property.
     */
    public CreateObjectRequest.Builder<_B> withCreateObject(final GenericObject createObject) {
      this.createObject = ((createObject == null) ? null : new GenericObject.Builder<>(this, createObject, false));
      return this;
    }

    /**
     * Sets the new value of "admfIdentifier" (any previous value will be replaced)
     *
     * @param admfIdentifier
     *     New value of the "admfIdentifier" property.
     */
    @Override
    public CreateObjectRequest.Builder<_B> withAdmfIdentifier(final String admfIdentifier) {
      super.withAdmfIdentifier(admfIdentifier);
      return this;
    }

    /**
     * Sets the new value of "neIdentifier" (any previous value will be replaced)
     *
     * @param neIdentifier
     *     New value of the "neIdentifier" property.
     */
    @Override
    public CreateObjectRequest.Builder<_B> withNeIdentifier(final String neIdentifier) {
      super.withNeIdentifier(neIdentifier);
      return this;
    }

    /**
     * Sets the new value of "messageTimestamp" (any previous value will be replaced)
     *
     * @param messageTimestamp
     *     New value of the "messageTimestamp" property.
     */
    @Override
    public CreateObjectRequest.Builder<_B> withMessageTimestamp(final XMLGregorianCalendar messageTimestamp) {
      super.withMessageTimestamp(messageTimestamp);
      return this;
    }

    /**
     * Sets the new value of "version" (any previous value will be replaced)
     *
     * @param version
     *     New value of the "version" property.
     */
    @Override
    public CreateObjectRequest.Builder<_B> withVersion(final String version) {
      super.withVersion(version);
      return this;
    }

    /**
     * Sets the new value of "x1TransactionId" (any previous value will be replaced)
     *
     * @param x1TransactionId
     *     New value of the "x1TransactionId" property.
     */
    @Override
    public CreateObjectRequest.Builder<_B> withX1TransactionId(final String x1TransactionId) {
      super.withX1TransactionId(x1TransactionId);
      return this;
    }

    @Override
    public CreateObjectRequest build() {
      if (_storedValue == null) {
        return this.init(new CreateObjectRequest());
      } else {
        return ((CreateObjectRequest) _storedValue);
      }
    }

    public CreateObjectRequest.Builder<_B> copyOf(final CreateObjectRequest _other) {
      _other.copyTo(this);
      return this;
    }

    public CreateObjectRequest.Builder<_B> copyOf(final CreateObjectRequest.Builder _other) {
      return copyOf(_other.build());
    }
  }

  public static class Select extends CreateObjectRequest.Selector<CreateObjectRequest.Select, Void> {

    Select() {
      super(null, null, null);
    }

    public static CreateObjectRequest.Select _root() {
      return new CreateObjectRequest.Select();
    }
  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
    extends X1RequestMessage.Selector<TRoot, TParent> {

    private GenericObject.Selector<TRoot, CreateObjectRequest.Selector<TRoot, TParent>> createObject = null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<>();
      products.putAll(super.buildChildren());
      if (this.createObject != null) {
        products.put("createObject", this.createObject.init());
      }
      return products;
    }

    public GenericObject.Selector<TRoot, CreateObjectRequest.Selector<TRoot, TParent>> createObject() {
      return (
        (this.createObject == null)
          ? this.createObject = new GenericObject.Selector<>(this._root, this, "createObject")
          : this.createObject
      );
    }
  }
}
