//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

/*
 * SPDX-License-Identifier: MIT
 */
package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PartialCopyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.HashMap;
import java.util.Map;
import org.etsi.uri._03280.common._2017._07.IPAddressPort;

/**
 * <p>Java class for DeliveryAddress complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="DeliveryAddress">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="ipAddressAndPort" type="{http://uri.etsi.org/03280/common/2017/07}IPAddressPort"/>
 *         <element name="e164Number" type="{http://uri.etsi.org/03280/common/2017/07}InternationalE164"/>
 *         <element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         <element name="emailAddress" type="{http://uri.etsi.org/03280/common/2017/07}EmailAddress"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryAddress", propOrder = { "ipAddressAndPort", "e164Number", "uri", "emailAddress" })
public class DeliveryAddress implements Copyable, PartialCopyable {

  protected IPAddressPort ipAddressAndPort;

  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "token")
  protected String e164Number;

  @XmlSchemaType(name = "anyURI")
  protected String uri;

  protected String emailAddress;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public DeliveryAddress() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a DeliveryAddress copying the state of another DeliveryAddress
   *
   * @param _other
   *     The original DeliveryAddress from which to copy state.
   */
  public DeliveryAddress(final DeliveryAddress _other) {
    this.ipAddressAndPort = ((_other.ipAddressAndPort == null) ? null : _other.ipAddressAndPort.createCopy());
    this.e164Number = _other.e164Number;
    this.uri = _other.uri;
    this.emailAddress = _other.emailAddress;
  }

  /**
   * Instantiates a DeliveryAddress copying the state of another DeliveryAddress
   *
   * @param _other
   *     The original DeliveryAddress from which to copy state.
   * @param _propertyTree
   *     A restricting {@link PropertyPath} that defines which nodes of the source object tree should actually be copied.
   * @param _propertyTreeUse
   *     Meaning of the {@link PropertyPath}: Exclude or include members contained in property path.
   */
  public DeliveryAddress(
    final DeliveryAddress _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final PropertyTree ipAddressAndPortPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("ipAddressAndPort"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (ipAddressAndPortPropertyTree != null)
          : ((ipAddressAndPortPropertyTree == null) || (!ipAddressAndPortPropertyTree.isLeaf())))
    ) {
      this.ipAddressAndPort = ((_other.ipAddressAndPort == null)
          ? null
          : _other.ipAddressAndPort.createCopy(ipAddressAndPortPropertyTree, _propertyTreeUse));
    }
    final PropertyTree e164NumberPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("e164Number"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (e164NumberPropertyTree != null)
          : ((e164NumberPropertyTree == null) || (!e164NumberPropertyTree.isLeaf())))
    ) {
      this.e164Number = _other.e164Number;
    }
    final PropertyTree uriPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("uri"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (uriPropertyTree != null)
          : ((uriPropertyTree == null) || (!uriPropertyTree.isLeaf())))
    ) {
      this.uri = _other.uri;
    }
    final PropertyTree emailAddressPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("emailAddress"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (emailAddressPropertyTree != null)
          : ((emailAddressPropertyTree == null) || (!emailAddressPropertyTree.isLeaf())))
    ) {
      this.emailAddress = _other.emailAddress;
    }
  }

  /**
   * Gets the value of the ipAddressAndPort property.
   *
   * @return
   *     possible object is
   *     {@link IPAddressPort }
   *
   */
  public IPAddressPort getIpAddressAndPort() {
    return ipAddressAndPort;
  }

  /**
   * Sets the value of the ipAddressAndPort property.
   *
   * @param value
   *     allowed object is
   *     {@link IPAddressPort }
   *
   */
  public void setIpAddressAndPort(IPAddressPort value) {
    this.ipAddressAndPort = value;
  }

  /**
   * Gets the value of the e164Number property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getE164Number() {
    return e164Number;
  }

  /**
   * Sets the value of the e164Number property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setE164Number(String value) {
    this.e164Number = value;
  }

  /**
   * Gets the value of the uri property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getUri() {
    return uri;
  }

  /**
   * Sets the value of the uri property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setUri(String value) {
    this.uri = value;
  }

  /**
   * Gets the value of the emailAddress property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getEmailAddress() {
    return emailAddress;
  }

  /**
   * Sets the value of the emailAddress property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setEmailAddress(String value) {
    this.emailAddress = value;
  }

  @Override
  public DeliveryAddress createCopy() {
    final DeliveryAddress _newObject;
    try {
      _newObject = ((DeliveryAddress) super.clone());
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
    _newObject.ipAddressAndPort = ((this.ipAddressAndPort == null) ? null : this.ipAddressAndPort.createCopy());
    _newObject.e164Number = this.e164Number;
    _newObject.uri = this.uri;
    _newObject.emailAddress = this.emailAddress;
    return _newObject;
  }

  @Override
  public DeliveryAddress createCopy(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
    final DeliveryAddress _newObject;
    try {
      _newObject = ((DeliveryAddress) super.clone());
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
    final PropertyTree ipAddressAndPortPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("ipAddressAndPort"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (ipAddressAndPortPropertyTree != null)
          : ((ipAddressAndPortPropertyTree == null) || (!ipAddressAndPortPropertyTree.isLeaf())))
    ) {
      _newObject.ipAddressAndPort = ((this.ipAddressAndPort == null)
          ? null
          : this.ipAddressAndPort.createCopy(ipAddressAndPortPropertyTree, _propertyTreeUse));
    }
    final PropertyTree e164NumberPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("e164Number"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (e164NumberPropertyTree != null)
          : ((e164NumberPropertyTree == null) || (!e164NumberPropertyTree.isLeaf())))
    ) {
      _newObject.e164Number = this.e164Number;
    }
    final PropertyTree uriPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("uri"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (uriPropertyTree != null)
          : ((uriPropertyTree == null) || (!uriPropertyTree.isLeaf())))
    ) {
      _newObject.uri = this.uri;
    }
    final PropertyTree emailAddressPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("emailAddress"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (emailAddressPropertyTree != null)
          : ((emailAddressPropertyTree == null) || (!emailAddressPropertyTree.isLeaf())))
    ) {
      _newObject.emailAddress = this.emailAddress;
    }
    return _newObject;
  }

  @Override
  public DeliveryAddress copyExcept(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.EXCLUDE);
  }

  @Override
  public DeliveryAddress copyOnly(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.INCLUDE);
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final DeliveryAddress.Builder<_B> _other) {
    _other.ipAddressAndPort = ((this.ipAddressAndPort == null) ? null : this.ipAddressAndPort.newCopyBuilder(_other));
    _other.e164Number = this.e164Number;
    _other.uri = this.uri;
    _other.emailAddress = this.emailAddress;
  }

  public <_B> DeliveryAddress.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new DeliveryAddress.Builder<_B>(_parentBuilder, this, true);
  }

  public DeliveryAddress.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static DeliveryAddress.Builder<Void> builder() {
    return new DeliveryAddress.Builder<>(null, null, false);
  }

  public static <_B> DeliveryAddress.Builder<_B> copyOf(final DeliveryAddress _other) {
    final DeliveryAddress.Builder<_B> _newBuilder = new DeliveryAddress.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final DeliveryAddress.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final PropertyTree ipAddressAndPortPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("ipAddressAndPort"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (ipAddressAndPortPropertyTree != null)
          : ((ipAddressAndPortPropertyTree == null) || (!ipAddressAndPortPropertyTree.isLeaf())))
    ) {
      _other.ipAddressAndPort = ((this.ipAddressAndPort == null)
          ? null
          : this.ipAddressAndPort.newCopyBuilder(_other, ipAddressAndPortPropertyTree, _propertyTreeUse));
    }
    final PropertyTree e164NumberPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("e164Number"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (e164NumberPropertyTree != null)
          : ((e164NumberPropertyTree == null) || (!e164NumberPropertyTree.isLeaf())))
    ) {
      _other.e164Number = this.e164Number;
    }
    final PropertyTree uriPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("uri"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (uriPropertyTree != null)
          : ((uriPropertyTree == null) || (!uriPropertyTree.isLeaf())))
    ) {
      _other.uri = this.uri;
    }
    final PropertyTree emailAddressPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("emailAddress"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (emailAddressPropertyTree != null)
          : ((emailAddressPropertyTree == null) || (!emailAddressPropertyTree.isLeaf())))
    ) {
      _other.emailAddress = this.emailAddress;
    }
  }

  public <_B> DeliveryAddress.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new DeliveryAddress.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  public DeliveryAddress.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> DeliveryAddress.Builder<_B> copyOf(
    final DeliveryAddress _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final DeliveryAddress.Builder<_B> _newBuilder = new DeliveryAddress.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static DeliveryAddress.Builder<Void> copyExcept(
    final DeliveryAddress _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static DeliveryAddress.Builder<Void> copyOnly(final DeliveryAddress _other, final PropertyTree _propertyTree) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> implements Buildable {

    protected final _B _parentBuilder;
    protected final DeliveryAddress _storedValue;
    private IPAddressPort.Builder<DeliveryAddress.Builder<_B>> ipAddressAndPort;
    private String e164Number;
    private String uri;
    private String emailAddress;

    public Builder(final _B _parentBuilder, final DeliveryAddress _other, final boolean _copy) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          this.ipAddressAndPort = ((_other.ipAddressAndPort == null)
              ? null
              : _other.ipAddressAndPort.newCopyBuilder(this));
          this.e164Number = _other.e164Number;
          this.uri = _other.uri;
          this.emailAddress = _other.emailAddress;
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public Builder(
      final _B _parentBuilder,
      final DeliveryAddress _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          final PropertyTree ipAddressAndPortPropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("ipAddressAndPort"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (ipAddressAndPortPropertyTree != null)
                : ((ipAddressAndPortPropertyTree == null) || (!ipAddressAndPortPropertyTree.isLeaf())))
          ) {
            this.ipAddressAndPort = ((_other.ipAddressAndPort == null)
                ? null
                : _other.ipAddressAndPort.newCopyBuilder(this, ipAddressAndPortPropertyTree, _propertyTreeUse));
          }
          final PropertyTree e164NumberPropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("e164Number"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (e164NumberPropertyTree != null)
                : ((e164NumberPropertyTree == null) || (!e164NumberPropertyTree.isLeaf())))
          ) {
            this.e164Number = _other.e164Number;
          }
          final PropertyTree uriPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("uri"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (uriPropertyTree != null)
                : ((uriPropertyTree == null) || (!uriPropertyTree.isLeaf())))
          ) {
            this.uri = _other.uri;
          }
          final PropertyTree emailAddressPropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("emailAddress"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (emailAddressPropertyTree != null)
                : ((emailAddressPropertyTree == null) || (!emailAddressPropertyTree.isLeaf())))
          ) {
            this.emailAddress = _other.emailAddress;
          }
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public _B end() {
      return this._parentBuilder;
    }

    protected <_P extends DeliveryAddress> _P init(final _P _product) {
      _product.ipAddressAndPort = ((this.ipAddressAndPort == null) ? null : this.ipAddressAndPort.build());
      _product.e164Number = this.e164Number;
      _product.uri = this.uri;
      _product.emailAddress = this.emailAddress;
      return _product;
    }

    /**
     * Sets the new value of "ipAddressAndPort" (any previous value will be replaced)
     *
     * @param ipAddressAndPort
     *     New value of the "ipAddressAndPort" property.
     */
    public DeliveryAddress.Builder<_B> withIpAddressAndPort(final IPAddressPort ipAddressAndPort) {
      this.ipAddressAndPort = ((ipAddressAndPort == null)
          ? null
          : new IPAddressPort.Builder<>(this, ipAddressAndPort, false));
      return this;
    }

    /**
     * Returns the existing builder or a new builder to build the value of the
     * "ipAddressAndPort" property.
     * Use {@link org.etsi.uri._03280.common._2017._07.IPAddressPort.Builder#end()} to
     * return to the current builder.
     *
     * @return
     *     A new builder to build the value of the "ipAddressAndPort" property.
     *     Use {@link org.etsi.uri._03280.common._2017._07.IPAddressPort.Builder#end()} to
     *     return to the current builder.
     */
    public IPAddressPort.Builder<? extends DeliveryAddress.Builder<_B>> withIpAddressAndPort() {
      if (this.ipAddressAndPort != null) {
        return this.ipAddressAndPort;
      }
      return this.ipAddressAndPort = new IPAddressPort.Builder<>(this, null, false);
    }

    /**
     * Sets the new value of "e164Number" (any previous value will be replaced)
     *
     * @param e164Number
     *     New value of the "e164Number" property.
     */
    public DeliveryAddress.Builder<_B> withE164Number(final String e164Number) {
      this.e164Number = e164Number;
      return this;
    }

    /**
     * Sets the new value of "uri" (any previous value will be replaced)
     *
     * @param uri
     *     New value of the "uri" property.
     */
    public DeliveryAddress.Builder<_B> withUri(final String uri) {
      this.uri = uri;
      return this;
    }

    /**
     * Sets the new value of "emailAddress" (any previous value will be replaced)
     *
     * @param emailAddress
     *     New value of the "emailAddress" property.
     */
    public DeliveryAddress.Builder<_B> withEmailAddress(final String emailAddress) {
      this.emailAddress = emailAddress;
      return this;
    }

    @Override
    public DeliveryAddress build() {
      if (_storedValue == null) {
        return this.init(new DeliveryAddress());
      } else {
        return ((DeliveryAddress) _storedValue);
      }
    }

    public DeliveryAddress.Builder<_B> copyOf(final DeliveryAddress _other) {
      _other.copyTo(this);
      return this;
    }

    public DeliveryAddress.Builder<_B> copyOf(final DeliveryAddress.Builder _other) {
      return copyOf(_other.build());
    }
  }

  public static class Select extends DeliveryAddress.Selector<DeliveryAddress.Select, Void> {

    Select() {
      super(null, null, null);
    }

    public static DeliveryAddress.Select _root() {
      return new DeliveryAddress.Select();
    }
  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
    extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

    private IPAddressPort.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> ipAddressAndPort = null;
    private com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> e164Number = null;
    private com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> uri = null;
    private com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> emailAddress = null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<>();
      products.putAll(super.buildChildren());
      if (this.ipAddressAndPort != null) {
        products.put("ipAddressAndPort", this.ipAddressAndPort.init());
      }
      if (this.e164Number != null) {
        products.put("e164Number", this.e164Number.init());
      }
      if (this.uri != null) {
        products.put("uri", this.uri.init());
      }
      if (this.emailAddress != null) {
        products.put("emailAddress", this.emailAddress.init());
      }
      return products;
    }

    public IPAddressPort.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> ipAddressAndPort() {
      return (
        (this.ipAddressAndPort == null)
          ? this.ipAddressAndPort = new IPAddressPort.Selector<>(this._root, this, "ipAddressAndPort")
          : this.ipAddressAndPort
      );
    }

    public com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> e164Number() {
      return (
        (this.e164Number == null)
          ? this.e164Number = new com.kscs.util.jaxb.Selector<>(this._root, this, "e164Number")
          : this.e164Number
      );
    }

    public com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> uri() {
      return ((this.uri == null) ? this.uri = new com.kscs.util.jaxb.Selector<>(this._root, this, "uri") : this.uri);
    }

    public com.kscs.util.jaxb.Selector<TRoot, DeliveryAddress.Selector<TRoot, TParent>> emailAddress() {
      return (
        (this.emailAddress == null)
          ? this.emailAddress = new com.kscs.util.jaxb.Selector<>(this._root, this, "emailAddress")
          : this.emailAddress
      );
    }
  }
}
