//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.etsi.uri._03221.x1._2017._10;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DestinationResponseDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DestinationResponseDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="destinationDetails" type="{http://uri.etsi.org/03221/X1/2017/10}DestinationDetails"/>
 *         <element name="destinationStatus" type="{http://uri.etsi.org/03221/X1/2017/10}DestinationStatus"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DestinationResponseDetails", propOrder = {
    "destinationDetails",
    "destinationStatus"
})
public class DestinationResponseDetails {

    @XmlElement(required = true)
    protected DestinationDetails destinationDetails;
    @XmlElement(required = true)
    protected DestinationStatus destinationStatus;

    /**
     * Gets the value of the destinationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationDetails }
     *     
     */
    public DestinationDetails getDestinationDetails() {
        return destinationDetails;
    }

    /**
     * Sets the value of the destinationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationDetails }
     *     
     */
    public void setDestinationDetails(DestinationDetails value) {
        this.destinationDetails = value;
    }

    /**
     * Gets the value of the destinationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationStatus }
     *     
     */
    public DestinationStatus getDestinationStatus() {
        return destinationStatus;
    }

    /**
     * Sets the value of the destinationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationStatus }
     *     
     */
    public void setDestinationStatus(DestinationStatus value) {
        this.destinationStatus = value;
    }

}
