//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for GenericObjectResponseDetails complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="GenericObjectResponseDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="object" type="{http://uri.etsi.org/03221/X1/2017/10}GenericObject"/>
 *         <element name="status" type="{http://uri.etsi.org/03221/X1/2017/10}GenericObjectStatus" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "GenericObjectResponseDetails",
  propOrder = { "object", "status" }
)
public class GenericObjectResponseDetails {

  @XmlElement(required = true)
  protected GenericObject object;

  protected GenericObjectStatus status;

  /**
   * Gets the value of the object property.
   *
   * @return
   *     possible object is
   *     {@link GenericObject }
   *
   */
  public GenericObject getObject() {
    return object;
  }

  /**
   * Sets the value of the object property.
   *
   * @param value
   *     allowed object is
   *     {@link GenericObject }
   *
   */
  public void setObject(GenericObject value) {
    this.object = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return
   *     possible object is
   *     {@link GenericObjectStatus }
   *
   */
  public GenericObjectStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value
   *     allowed object is
   *     {@link GenericObjectStatus }
   *
   */
  public void setStatus(GenericObjectStatus value) {
    this.status = value;
  }
}
