//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for GetAllGenericObjectDetailsRequest complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="GetAllGenericObjectDetailsRequest">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1RequestMessage">
 *       <sequence>
 *         <element name="objectType" type="{http://uri.etsi.org/03221/X1/2017/10}GenericObjectType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAllGenericObjectDetailsRequest", propOrder = { "objectType" })
public class GetAllGenericObjectDetailsRequest extends X1RequestMessage implements Copyable {

  protected String objectType;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public GetAllGenericObjectDetailsRequest() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a GetAllGenericObjectDetailsRequest copying the state of another GetAllGenericObjectDetailsRequest
   *
   * @param _other
   *     The original GetAllGenericObjectDetailsRequest from which to copy state.
   */
  public GetAllGenericObjectDetailsRequest(final GetAllGenericObjectDetailsRequest _other) {
    super(_other);
    this.objectType = _other.objectType;
  }

  /**
   * Gets the value of the objectType property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the objectType property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setObjectType(String value) {
    this.objectType = value;
  }

  @Override
  public GetAllGenericObjectDetailsRequest createCopy() {
    final GetAllGenericObjectDetailsRequest _newObject = ((GetAllGenericObjectDetailsRequest) super.createCopy());
    _newObject.objectType = this.objectType;
    return _newObject;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final GetAllGenericObjectDetailsRequest.Builder<_B> _other) {
    super.copyTo(_other);
    _other.objectType = this.objectType;
  }

  @Override
  public <_B> GetAllGenericObjectDetailsRequest.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new GetAllGenericObjectDetailsRequest.Builder<_B>(_parentBuilder, this, true);
  }

  @Override
  public GetAllGenericObjectDetailsRequest.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static GetAllGenericObjectDetailsRequest.Builder<Void> builder() {
    return new GetAllGenericObjectDetailsRequest.Builder<>(null, null, false);
  }

  public static <_B> GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(final X1RequestMessage _other) {
    final GetAllGenericObjectDetailsRequest.Builder<_B> _newBuilder = new GetAllGenericObjectDetailsRequest.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  public static <_B> GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(
    final GetAllGenericObjectDetailsRequest _other
  ) {
    final GetAllGenericObjectDetailsRequest.Builder<_B> _newBuilder = new GetAllGenericObjectDetailsRequest.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final GetAllGenericObjectDetailsRequest.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super.copyTo(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree objectTypePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("objectType"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (objectTypePropertyTree != null)
          : ((objectTypePropertyTree == null) || (!objectTypePropertyTree.isLeaf())))
    ) {
      _other.objectType = this.objectType;
    }
  }

  @Override
  public <_B> GetAllGenericObjectDetailsRequest.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new GetAllGenericObjectDetailsRequest.Builder<_B>(
      _parentBuilder,
      this,
      true,
      _propertyTree,
      _propertyTreeUse
    );
  }

  @Override
  public GetAllGenericObjectDetailsRequest.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final GetAllGenericObjectDetailsRequest.Builder<_B> _newBuilder = new GetAllGenericObjectDetailsRequest.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static <_B> GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(
    final GetAllGenericObjectDetailsRequest _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final GetAllGenericObjectDetailsRequest.Builder<_B> _newBuilder = new GetAllGenericObjectDetailsRequest.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static GetAllGenericObjectDetailsRequest.Builder<Void> copyExcept(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static GetAllGenericObjectDetailsRequest.Builder<Void> copyExcept(
    final GetAllGenericObjectDetailsRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static GetAllGenericObjectDetailsRequest.Builder<Void> copyOnly(
    final X1RequestMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static GetAllGenericObjectDetailsRequest.Builder<Void> copyOnly(
    final GetAllGenericObjectDetailsRequest _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> extends X1RequestMessage.Builder<_B> implements Buildable {

    private String objectType;

    public Builder(final _B _parentBuilder, final GetAllGenericObjectDetailsRequest _other, final boolean _copy) {
      super(_parentBuilder, _other, _copy);
      if (_other != null) {
        this.objectType = _other.objectType;
      }
    }

    public Builder(
      final _B _parentBuilder,
      final GetAllGenericObjectDetailsRequest _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
      if (_other != null) {
        final PropertyTree objectTypePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("objectType"));
        if (
          ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (objectTypePropertyTree != null)
              : ((objectTypePropertyTree == null) || (!objectTypePropertyTree.isLeaf())))
        ) {
          this.objectType = _other.objectType;
        }
      }
    }

    protected <_P extends GetAllGenericObjectDetailsRequest> _P init(final _P _product) {
      _product.objectType = this.objectType;
      return super.init(_product);
    }

    /**
     * Sets the new value of "objectType" (any previous value will be replaced)
     *
     * @param objectType
     *     New value of the "objectType" property.
     */
    public GetAllGenericObjectDetailsRequest.Builder<_B> withObjectType(final String objectType) {
      this.objectType = objectType;
      return this;
    }

    /**
     * Sets the new value of "admfIdentifier" (any previous value will be replaced)
     *
     * @param admfIdentifier
     *     New value of the "admfIdentifier" property.
     */
    @Override
    public GetAllGenericObjectDetailsRequest.Builder<_B> withAdmfIdentifier(final String admfIdentifier) {
      super.withAdmfIdentifier(admfIdentifier);
      return this;
    }

    /**
     * Sets the new value of "neIdentifier" (any previous value will be replaced)
     *
     * @param neIdentifier
     *     New value of the "neIdentifier" property.
     */
    @Override
    public GetAllGenericObjectDetailsRequest.Builder<_B> withNeIdentifier(final String neIdentifier) {
      super.withNeIdentifier(neIdentifier);
      return this;
    }

    /**
     * Sets the new value of "messageTimestamp" (any previous value will be replaced)
     *
     * @param messageTimestamp
     *     New value of the "messageTimestamp" property.
     */
    @Override
    public GetAllGenericObjectDetailsRequest.Builder<_B> withMessageTimestamp(
      final XMLGregorianCalendar messageTimestamp
    ) {
      super.withMessageTimestamp(messageTimestamp);
      return this;
    }

    /**
     * Sets the new value of "version" (any previous value will be replaced)
     *
     * @param version
     *     New value of the "version" property.
     */
    @Override
    public GetAllGenericObjectDetailsRequest.Builder<_B> withVersion(final String version) {
      super.withVersion(version);
      return this;
    }

    /**
     * Sets the new value of "x1TransactionId" (any previous value will be replaced)
     *
     * @param x1TransactionId
     *     New value of the "x1TransactionId" property.
     */
    @Override
    public GetAllGenericObjectDetailsRequest.Builder<_B> withX1TransactionId(final String x1TransactionId) {
      super.withX1TransactionId(x1TransactionId);
      return this;
    }

    @Override
    public GetAllGenericObjectDetailsRequest build() {
      if (_storedValue == null) {
        return this.init(new GetAllGenericObjectDetailsRequest());
      } else {
        return ((GetAllGenericObjectDetailsRequest) _storedValue);
      }
    }

    public GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(final GetAllGenericObjectDetailsRequest _other) {
      _other.copyTo(this);
      return this;
    }

    public GetAllGenericObjectDetailsRequest.Builder<_B> copyOf(
      final GetAllGenericObjectDetailsRequest.Builder _other
    ) {
      return copyOf(_other.build());
    }
  }
}
