//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

/*
 * SPDX-License-Identifier: MIT
 */
package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PartialCopyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for GetNEStatusResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="GetNEStatusResponse">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1ResponseMessage">
 *       <sequence>
 *         <element name="neStatusDetails" type="{http://uri.etsi.org/03221/X1/2017/10}NeStatusDetails"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetNEStatusResponse", propOrder = { "neStatusDetails" })
public class GetNEStatusResponse extends X1ResponseMessage implements Copyable, PartialCopyable {

  @XmlElement(required = true)
  protected NeStatusDetails neStatusDetails;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public GetNEStatusResponse() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a GetNEStatusResponse copying the state of another GetNEStatusResponse
   *
   * @param _other
   *     The original GetNEStatusResponse from which to copy state.
   */
  public GetNEStatusResponse(final GetNEStatusResponse _other) {
    super(_other);
    this.neStatusDetails = ((_other.neStatusDetails == null) ? null : _other.neStatusDetails.createCopy());
  }

  /**
   * Instantiates a GetNEStatusResponse copying the state of another GetNEStatusResponse
   *
   * @param _other
   *     The original GetNEStatusResponse from which to copy state.
   * @param _propertyTree
   *     A restricting {@link PropertyPath} that defines which nodes of the source object tree should actually be copied.
   * @param _propertyTreeUse
   *     Meaning of the {@link PropertyPath}: Exclude or include members contained in property path.
   */
  public GetNEStatusResponse(
    final GetNEStatusResponse _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree neStatusDetailsPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("neStatusDetails"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (neStatusDetailsPropertyTree != null)
          : ((neStatusDetailsPropertyTree == null) || (!neStatusDetailsPropertyTree.isLeaf())))
    ) {
      this.neStatusDetails = ((_other.neStatusDetails == null)
          ? null
          : _other.neStatusDetails.createCopy(neStatusDetailsPropertyTree, _propertyTreeUse));
    }
  }

  /**
   * Gets the value of the neStatusDetails property.
   *
   * @return
   *     possible object is
   *     {@link NeStatusDetails }
   *
   */
  public NeStatusDetails getNeStatusDetails() {
    return neStatusDetails;
  }

  /**
   * Sets the value of the neStatusDetails property.
   *
   * @param value
   *     allowed object is
   *     {@link NeStatusDetails }
   *
   */
  public void setNeStatusDetails(NeStatusDetails value) {
    this.neStatusDetails = value;
  }

  @Override
  public GetNEStatusResponse createCopy() {
    final GetNEStatusResponse _newObject = ((GetNEStatusResponse) super.createCopy());
    _newObject.neStatusDetails = ((this.neStatusDetails == null) ? null : this.neStatusDetails.createCopy());
    return _newObject;
  }

  @Override
  public GetNEStatusResponse createCopy(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
    final GetNEStatusResponse _newObject = ((GetNEStatusResponse) super.createCopy(_propertyTree, _propertyTreeUse));
    final PropertyTree neStatusDetailsPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("neStatusDetails"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (neStatusDetailsPropertyTree != null)
          : ((neStatusDetailsPropertyTree == null) || (!neStatusDetailsPropertyTree.isLeaf())))
    ) {
      _newObject.neStatusDetails = ((this.neStatusDetails == null)
          ? null
          : this.neStatusDetails.createCopy(neStatusDetailsPropertyTree, _propertyTreeUse));
    }
    return _newObject;
  }

  @Override
  public GetNEStatusResponse copyExcept(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.EXCLUDE);
  }

  @Override
  public GetNEStatusResponse copyOnly(final PropertyTree _propertyTree) {
    return createCopy(_propertyTree, PropertyTreeUse.INCLUDE);
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final GetNEStatusResponse.Builder<_B> _other) {
    super.copyTo(_other);
    _other.neStatusDetails = ((this.neStatusDetails == null) ? null : this.neStatusDetails.newCopyBuilder(_other));
  }

  @Override
  public <_B> GetNEStatusResponse.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new GetNEStatusResponse.Builder<_B>(_parentBuilder, this, true);
  }

  @Override
  public GetNEStatusResponse.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static GetNEStatusResponse.Builder<Void> builder() {
    return new GetNEStatusResponse.Builder<>(null, null, false);
  }

  public static <_B> GetNEStatusResponse.Builder<_B> copyOf(final X1ResponseMessage _other) {
    final GetNEStatusResponse.Builder<_B> _newBuilder = new GetNEStatusResponse.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  public static <_B> GetNEStatusResponse.Builder<_B> copyOf(final GetNEStatusResponse _other) {
    final GetNEStatusResponse.Builder<_B> _newBuilder = new GetNEStatusResponse.Builder<>(null, null, false);
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final GetNEStatusResponse.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    super.copyTo(_other, _propertyTree, _propertyTreeUse);
    final PropertyTree neStatusDetailsPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("neStatusDetails"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (neStatusDetailsPropertyTree != null)
          : ((neStatusDetailsPropertyTree == null) || (!neStatusDetailsPropertyTree.isLeaf())))
    ) {
      _other.neStatusDetails = ((this.neStatusDetails == null)
          ? null
          : this.neStatusDetails.newCopyBuilder(_other, neStatusDetailsPropertyTree, _propertyTreeUse));
    }
  }

  @Override
  public <_B> GetNEStatusResponse.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new GetNEStatusResponse.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  @Override
  public GetNEStatusResponse.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> GetNEStatusResponse.Builder<_B> copyOf(
    final X1ResponseMessage _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final GetNEStatusResponse.Builder<_B> _newBuilder = new GetNEStatusResponse.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static <_B> GetNEStatusResponse.Builder<_B> copyOf(
    final GetNEStatusResponse _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final GetNEStatusResponse.Builder<_B> _newBuilder = new GetNEStatusResponse.Builder<>(null, null, false);
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static GetNEStatusResponse.Builder<Void> copyExcept(
    final X1ResponseMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static GetNEStatusResponse.Builder<Void> copyExcept(
    final GetNEStatusResponse _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static GetNEStatusResponse.Builder<Void> copyOnly(
    final X1ResponseMessage _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static GetNEStatusResponse.Builder<Void> copyOnly(
    final GetNEStatusResponse _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> extends X1ResponseMessage.Builder<_B> implements Buildable {

    private NeStatusDetails.Builder<GetNEStatusResponse.Builder<_B>> neStatusDetails;

    public Builder(final _B _parentBuilder, final GetNEStatusResponse _other, final boolean _copy) {
      super(_parentBuilder, _other, _copy);
      if (_other != null) {
        this.neStatusDetails = ((_other.neStatusDetails == null) ? null : _other.neStatusDetails.newCopyBuilder(this));
      }
    }

    public Builder(
      final _B _parentBuilder,
      final GetNEStatusResponse _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
      if (_other != null) {
        final PropertyTree neStatusDetailsPropertyTree =
          ((_propertyTree == null) ? null : _propertyTree.get("neStatusDetails"));
        if (
          ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
              ? (neStatusDetailsPropertyTree != null)
              : ((neStatusDetailsPropertyTree == null) || (!neStatusDetailsPropertyTree.isLeaf())))
        ) {
          this.neStatusDetails = ((_other.neStatusDetails == null)
              ? null
              : _other.neStatusDetails.newCopyBuilder(this, neStatusDetailsPropertyTree, _propertyTreeUse));
        }
      }
    }

    protected <_P extends GetNEStatusResponse> _P init(final _P _product) {
      _product.neStatusDetails = ((this.neStatusDetails == null) ? null : this.neStatusDetails.build());
      return super.init(_product);
    }

    /**
     * Sets the new value of "neStatusDetails" (any previous value will be replaced)
     *
     * @param neStatusDetails
     *     New value of the "neStatusDetails" property.
     */
    public GetNEStatusResponse.Builder<_B> withNeStatusDetails(final NeStatusDetails neStatusDetails) {
      this.neStatusDetails = ((neStatusDetails == null)
          ? null
          : new NeStatusDetails.Builder<>(this, neStatusDetails, false));
      return this;
    }

    /**
     * Returns the existing builder or a new builder to build the value of the
     * "neStatusDetails" property.
     * Use {@link org.etsi.uri._03221.x1._2017._10.NeStatusDetails.Builder#end()} to
     * return to the current builder.
     *
     * @return
     *     A new builder to build the value of the "neStatusDetails" property.
     *     Use {@link org.etsi.uri._03221.x1._2017._10.NeStatusDetails.Builder#end()} to
     *     return to the current builder.
     */
    public NeStatusDetails.Builder<? extends GetNEStatusResponse.Builder<_B>> withNeStatusDetails() {
      if (this.neStatusDetails != null) {
        return this.neStatusDetails;
      }
      return this.neStatusDetails = new NeStatusDetails.Builder<>(this, null, false);
    }

    /**
     * Sets the new value of "admfIdentifier" (any previous value will be replaced)
     *
     * @param admfIdentifier
     *     New value of the "admfIdentifier" property.
     */
    @Override
    public GetNEStatusResponse.Builder<_B> withAdmfIdentifier(final String admfIdentifier) {
      super.withAdmfIdentifier(admfIdentifier);
      return this;
    }

    /**
     * Sets the new value of "neIdentifier" (any previous value will be replaced)
     *
     * @param neIdentifier
     *     New value of the "neIdentifier" property.
     */
    @Override
    public GetNEStatusResponse.Builder<_B> withNeIdentifier(final String neIdentifier) {
      super.withNeIdentifier(neIdentifier);
      return this;
    }

    /**
     * Sets the new value of "messageTimestamp" (any previous value will be replaced)
     *
     * @param messageTimestamp
     *     New value of the "messageTimestamp" property.
     */
    @Override
    public GetNEStatusResponse.Builder<_B> withMessageTimestamp(final XMLGregorianCalendar messageTimestamp) {
      super.withMessageTimestamp(messageTimestamp);
      return this;
    }

    /**
     * Sets the new value of "version" (any previous value will be replaced)
     *
     * @param version
     *     New value of the "version" property.
     */
    @Override
    public GetNEStatusResponse.Builder<_B> withVersion(final String version) {
      super.withVersion(version);
      return this;
    }

    /**
     * Sets the new value of "x1TransactionId" (any previous value will be replaced)
     *
     * @param x1TransactionId
     *     New value of the "x1TransactionId" property.
     */
    @Override
    public GetNEStatusResponse.Builder<_B> withX1TransactionId(final String x1TransactionId) {
      super.withX1TransactionId(x1TransactionId);
      return this;
    }

    @Override
    public GetNEStatusResponse build() {
      if (_storedValue == null) {
        return this.init(new GetNEStatusResponse());
      } else {
        return ((GetNEStatusResponse) _storedValue);
      }
    }

    public GetNEStatusResponse.Builder<_B> copyOf(final GetNEStatusResponse _other) {
      _other.copyTo(this);
      return this;
    }

    public GetNEStatusResponse.Builder<_B> copyOf(final GetNEStatusResponse.Builder _other) {
      return copyOf(_other.build());
    }
  }

  public static class Select extends GetNEStatusResponse.Selector<GetNEStatusResponse.Select, Void> {

    Select() {
      super(null, null, null);
    }

    public static GetNEStatusResponse.Select _root() {
      return new GetNEStatusResponse.Select();
    }
  }

  public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
    extends X1ResponseMessage.Selector<TRoot, TParent> {

    private NeStatusDetails.Selector<TRoot, GetNEStatusResponse.Selector<TRoot, TParent>> neStatusDetails = null;

    public Selector(final TRoot root, final TParent parent, final String propertyName) {
      super(root, parent, propertyName);
    }

    @Override
    public Map<String, PropertyTree> buildChildren() {
      final Map<String, PropertyTree> products = new HashMap<>();
      products.putAll(super.buildChildren());
      if (this.neStatusDetails != null) {
        products.put("neStatusDetails", this.neStatusDetails.init());
      }
      return products;
    }

    public NeStatusDetails.Selector<TRoot, GetNEStatusResponse.Selector<TRoot, TParent>> neStatusDetails() {
      return (
        (this.neStatusDetails == null)
          ? this.neStatusDetails = new NeStatusDetails.Selector<>(this._root, this, "neStatusDetails")
          : this.neStatusDetails
      );
    }
  }
}
