//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * <p>Java class for ListOfTaskResponseDetails complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="ListOfTaskResponseDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="taskResponseDetails" type="{http://uri.etsi.org/03221/X1/2017/10}TaskResponseDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfTaskResponseDetails", propOrder = { "taskResponseDetails" })
public class ListOfTaskResponseDetails implements Copyable {

  protected List<TaskResponseDetails> taskResponseDetails;

  /**
   * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
   *
   */
  public ListOfTaskResponseDetails() {
    // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
  }

  /**
   * Instantiates a ListOfTaskResponseDetails copying the state of another ListOfTaskResponseDetails
   *
   * @param _other
   *     The original ListOfTaskResponseDetails from which to copy state.
   */
  public ListOfTaskResponseDetails(final ListOfTaskResponseDetails _other) {
    if (_other.taskResponseDetails == null) {
      this.taskResponseDetails = null;
    } else {
      this.taskResponseDetails = new ArrayList<>();
      for (TaskResponseDetails _item : _other.taskResponseDetails) {
        this.taskResponseDetails.add(((_item == null) ? null : _item.createCopy()));
      }
    }
  }

  /**
   * Gets the value of the taskResponseDetails property.
   *
   * <p>This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the taskResponseDetails property.</p>
   *
   * <p>
   * For example, to add a new item, do as follows:
   * </p>
   * <pre>
   * getTaskResponseDetails().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TaskResponseDetails }
   * </p>
   *
   *
   * @return
   *     The value of the taskResponseDetails property.
   */
  public List<TaskResponseDetails> getTaskResponseDetails() {
    if (taskResponseDetails == null) {
      taskResponseDetails = new ArrayList<>();
    }
    return this.taskResponseDetails;
  }

  @Override
  public ListOfTaskResponseDetails createCopy() {
    final ListOfTaskResponseDetails _newObject;
    try {
      _newObject = ((ListOfTaskResponseDetails) super.clone());
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
    if (this.taskResponseDetails == null) {
      _newObject.taskResponseDetails = null;
    } else {
      _newObject.taskResponseDetails = new ArrayList<>();
      for (TaskResponseDetails _item : this.taskResponseDetails) {
        _newObject.taskResponseDetails.add(((_item == null) ? null : _item.createCopy()));
      }
    }
    return _newObject;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(final ListOfTaskResponseDetails.Builder<_B> _other) {
    if (this.taskResponseDetails == null) {
      _other.taskResponseDetails = null;
    } else {
      _other.taskResponseDetails = new ArrayList<>();
      for (TaskResponseDetails _item : this.taskResponseDetails) {
        _other.taskResponseDetails.add(((_item == null) ? null : _item.newCopyBuilder(_other)));
      }
    }
  }

  public <_B> ListOfTaskResponseDetails.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
    return new ListOfTaskResponseDetails.Builder<_B>(_parentBuilder, this, true);
  }

  public ListOfTaskResponseDetails.Builder<Void> newCopyBuilder() {
    return newCopyBuilder(null);
  }

  public static ListOfTaskResponseDetails.Builder<Void> builder() {
    return new ListOfTaskResponseDetails.Builder<>(null, null, false);
  }

  public static <_B> ListOfTaskResponseDetails.Builder<_B> copyOf(final ListOfTaskResponseDetails _other) {
    final ListOfTaskResponseDetails.Builder<_B> _newBuilder = new ListOfTaskResponseDetails.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder);
    return _newBuilder;
  }

  /**
   * Copies all state of this object to a builder. This method is used by the copyOf
   * method and should not be called directly by client code.
   *
   * @param _other
   *     A builder instance to which the state of this object will be copied.
   */
  public <_B> void copyTo(
    final ListOfTaskResponseDetails.Builder<_B> _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final PropertyTree taskResponseDetailsPropertyTree =
      ((_propertyTree == null) ? null : _propertyTree.get("taskResponseDetails"));
    if (
      ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
          ? (taskResponseDetailsPropertyTree != null)
          : ((taskResponseDetailsPropertyTree == null) || (!taskResponseDetailsPropertyTree.isLeaf())))
    ) {
      if (this.taskResponseDetails == null) {
        _other.taskResponseDetails = null;
      } else {
        _other.taskResponseDetails = new ArrayList<>();
        for (TaskResponseDetails _item : this.taskResponseDetails) {
          _other.taskResponseDetails.add(
            ((_item == null) ? null : _item.newCopyBuilder(_other, taskResponseDetailsPropertyTree, _propertyTreeUse))
          );
        }
      }
    }
  }

  public <_B> ListOfTaskResponseDetails.Builder<_B> newCopyBuilder(
    final _B _parentBuilder,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return new ListOfTaskResponseDetails.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
  }

  public ListOfTaskResponseDetails.Builder<Void> newCopyBuilder(
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
  }

  public static <_B> ListOfTaskResponseDetails.Builder<_B> copyOf(
    final ListOfTaskResponseDetails _other,
    final PropertyTree _propertyTree,
    final PropertyTreeUse _propertyTreeUse
  ) {
    final ListOfTaskResponseDetails.Builder<_B> _newBuilder = new ListOfTaskResponseDetails.Builder<>(
      null,
      null,
      false
    );
    _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
    return _newBuilder;
  }

  public static ListOfTaskResponseDetails.Builder<Void> copyExcept(
    final ListOfTaskResponseDetails _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
  }

  public static ListOfTaskResponseDetails.Builder<Void> copyOnly(
    final ListOfTaskResponseDetails _other,
    final PropertyTree _propertyTree
  ) {
    return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
  }

  public static class Builder<_B> implements Buildable {

    protected final _B _parentBuilder;
    protected final ListOfTaskResponseDetails _storedValue;
    private List<TaskResponseDetails.Builder<ListOfTaskResponseDetails.Builder<_B>>> taskResponseDetails;

    public Builder(final _B _parentBuilder, final ListOfTaskResponseDetails _other, final boolean _copy) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          if (_other.taskResponseDetails == null) {
            this.taskResponseDetails = null;
          } else {
            this.taskResponseDetails = new ArrayList<>();
            for (TaskResponseDetails _item : _other.taskResponseDetails) {
              this.taskResponseDetails.add(((_item == null) ? null : _item.newCopyBuilder(this)));
            }
          }
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public Builder(
      final _B _parentBuilder,
      final ListOfTaskResponseDetails _other,
      final boolean _copy,
      final PropertyTree _propertyTree,
      final PropertyTreeUse _propertyTreeUse
    ) {
      this._parentBuilder = _parentBuilder;
      if (_other != null) {
        if (_copy) {
          _storedValue = null;
          final PropertyTree taskResponseDetailsPropertyTree =
            ((_propertyTree == null) ? null : _propertyTree.get("taskResponseDetails"));
          if (
            ((_propertyTreeUse == PropertyTreeUse.INCLUDE)
                ? (taskResponseDetailsPropertyTree != null)
                : ((taskResponseDetailsPropertyTree == null) || (!taskResponseDetailsPropertyTree.isLeaf())))
          ) {
            if (_other.taskResponseDetails == null) {
              this.taskResponseDetails = null;
            } else {
              this.taskResponseDetails = new ArrayList<>();
              for (TaskResponseDetails _item : _other.taskResponseDetails) {
                this.taskResponseDetails.add(
                    ((_item == null)
                        ? null
                        : _item.newCopyBuilder(this, taskResponseDetailsPropertyTree, _propertyTreeUse))
                  );
              }
            }
          }
        } else {
          _storedValue = _other;
        }
      } else {
        _storedValue = null;
      }
    }

    public _B end() {
      return this._parentBuilder;
    }

    protected <_P extends ListOfTaskResponseDetails> _P init(final _P _product) {
      if (this.taskResponseDetails != null) {
        final List<TaskResponseDetails> taskResponseDetails = new ArrayList<>(this.taskResponseDetails.size());
        for (TaskResponseDetails.Builder<ListOfTaskResponseDetails.Builder<_B>> _item : this.taskResponseDetails) {
          taskResponseDetails.add(_item.build());
        }
        _product.taskResponseDetails = taskResponseDetails;
      }
      return _product;
    }

    /**
     * Adds the given items to the value of "taskResponseDetails"
     *
     * @param taskResponseDetails
     *     Items to add to the value of the "taskResponseDetails" property
     */
    public ListOfTaskResponseDetails.Builder<_B> addTaskResponseDetails(
      final Iterable<? extends TaskResponseDetails> taskResponseDetails
    ) {
      if (taskResponseDetails != null) {
        if (this.taskResponseDetails == null) {
          this.taskResponseDetails = new ArrayList<>();
        }
        for (TaskResponseDetails _item : taskResponseDetails) {
          this.taskResponseDetails.add(new TaskResponseDetails.Builder<>(this, _item, false));
        }
      }
      return this;
    }

    /**
     * Sets the new value of "taskResponseDetails" (any previous value will be
     * replaced)
     *
     * @param taskResponseDetails
     *     New value of the "taskResponseDetails" property.
     */
    public ListOfTaskResponseDetails.Builder<_B> withTaskResponseDetails(
      final Iterable<? extends TaskResponseDetails> taskResponseDetails
    ) {
      if (this.taskResponseDetails != null) {
        this.taskResponseDetails.clear();
      }
      return addTaskResponseDetails(taskResponseDetails);
    }

    /**
     * Adds the given items to the value of "taskResponseDetails"
     *
     * @param taskResponseDetails
     *     Items to add to the value of the "taskResponseDetails" property
     */
    public ListOfTaskResponseDetails.Builder<_B> addTaskResponseDetails(TaskResponseDetails... taskResponseDetails) {
      addTaskResponseDetails(Arrays.asList(taskResponseDetails));
      return this;
    }

    /**
     * Sets the new value of "taskResponseDetails" (any previous value will be
     * replaced)
     *
     * @param taskResponseDetails
     *     New value of the "taskResponseDetails" property.
     */
    public ListOfTaskResponseDetails.Builder<_B> withTaskResponseDetails(TaskResponseDetails... taskResponseDetails) {
      withTaskResponseDetails(Arrays.asList(taskResponseDetails));
      return this;
    }

    /**
     * Returns a new builder to build an additional value of the "TaskResponseDetails"
     * property.
     * Use {@link org.etsi.uri._03221.x1._2017._10.TaskResponseDetails.Builder#end()}
     * to return to the current builder.
     *
     * @return
     *     a new builder to build an additional value of the "TaskResponseDetails"
     *     property.
     *     Use {@link org.etsi.uri._03221.x1._2017._10.TaskResponseDetails.Builder#end()}
     *     to return to the current builder.
     */
    public TaskResponseDetails.Builder<? extends ListOfTaskResponseDetails.Builder<_B>> addTaskResponseDetails() {
      if (this.taskResponseDetails == null) {
        this.taskResponseDetails = new ArrayList<>();
      }
      final TaskResponseDetails.Builder<ListOfTaskResponseDetails.Builder<_B>> taskResponseDetails_Builder =
        new TaskResponseDetails.Builder<>(this, null, false);
      this.taskResponseDetails.add(taskResponseDetails_Builder);
      return taskResponseDetails_Builder;
    }

    @Override
    public ListOfTaskResponseDetails build() {
      if (_storedValue == null) {
        return this.init(new ListOfTaskResponseDetails());
      } else {
        return ((ListOfTaskResponseDetails) _storedValue);
      }
    }

    public ListOfTaskResponseDetails.Builder<_B> copyOf(final ListOfTaskResponseDetails _other) {
      _other.copyTo(this);
      return this;
    }

    public ListOfTaskResponseDetails.Builder<_B> copyOf(final ListOfTaskResponseDetails.Builder _other) {
      return copyOf(_other.build());
    }
  }
}
