//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.etsi.uri._03221.x1._2017._10;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListObjectsOfTypeResponse complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ListObjectsOfTypeResponse">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1ResponseMessage">
 *       <sequence>
 *         <element name="listOfObjects" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfGenericObjectIDs"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListObjectsOfTypeResponse", propOrder = {
    "listOfObjects"
})
public class ListObjectsOfTypeResponse
    extends X1ResponseMessage
{

    @XmlElement(required = true)
    protected ListOfGenericObjectIDs listOfObjects;

    /**
     * Gets the value of the listOfObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfGenericObjectIDs }
     *     
     */
    public ListOfGenericObjectIDs getListOfObjects() {
        return listOfObjects;
    }

    /**
     * Sets the value of the listOfObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfGenericObjectIDs }
     *     
     */
    public void setListOfObjects(ListOfGenericObjectIDs value) {
        this.listOfObjects = value;
    }

}
