//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ListObjectsOfTypeRequest complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="ListObjectsOfTypeRequest">
 *   <complexContent>
 *     <extension base="{http://uri.etsi.org/03221/X1/2017/10}X1RequestMessage">
 *       <sequence>
 *         <element name="objectType" type="{http://uri.etsi.org/03221/X1/2017/10}GenericObjectType"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListObjectsOfTypeRequest", propOrder = { "objectType" })
public class ListObjectsOfTypeRequest extends X1RequestMessage {

  @XmlElement(required = true)
  protected String objectType;

  /**
   * Gets the value of the objectType property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getObjectType() {
    return objectType;
  }

  /**
   * Sets the value of the objectType property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setObjectType(String value) {
    this.objectType = value;
  }
}
