//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package org.etsi.uri._03221.x1._2017._10;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ServiceScopingOptions complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="ServiceScopingOptions">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="serviceType" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfServiceTypes" minOccurs="0"/>
 *         <element name="locationType" type="{http://uri.etsi.org/03221/X1/2017/10}LocationTypeOptions" minOccurs="0"/>
 *         <element name="suspendOnOutboundInternationalRoaming" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="reportPostDialledDigits" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "ServiceScopingOptions",
  propOrder = {
    "serviceType",
    "locationType",
    "suspendOnOutboundInternationalRoaming",
    "reportPostDialledDigits",
  }
)
public class ServiceScopingOptions {

  protected ListOfServiceTypes serviceType;
  protected LocationTypeOptions locationType;
  protected Boolean suspendOnOutboundInternationalRoaming;
  protected Boolean reportPostDialledDigits;

  /**
   * Gets the value of the serviceType property.
   *
   * @return
   *     possible object is
   *     {@link ListOfServiceTypes }
   *
   */
  public ListOfServiceTypes getServiceType() {
    return serviceType;
  }

  /**
   * Sets the value of the serviceType property.
   *
   * @param value
   *     allowed object is
   *     {@link ListOfServiceTypes }
   *
   */
  public void setServiceType(ListOfServiceTypes value) {
    this.serviceType = value;
  }

  /**
   * Gets the value of the locationType property.
   *
   * @return
   *     possible object is
   *     {@link LocationTypeOptions }
   *
   */
  public LocationTypeOptions getLocationType() {
    return locationType;
  }

  /**
   * Sets the value of the locationType property.
   *
   * @param value
   *     allowed object is
   *     {@link LocationTypeOptions }
   *
   */
  public void setLocationType(LocationTypeOptions value) {
    this.locationType = value;
  }

  /**
   * Gets the value of the suspendOnOutboundInternationalRoaming property.
   *
   * @return
   *     possible object is
   *     {@link Boolean }
   *
   */
  public Boolean isSuspendOnOutboundInternationalRoaming() {
    return suspendOnOutboundInternationalRoaming;
  }

  /**
   * Sets the value of the suspendOnOutboundInternationalRoaming property.
   *
   * @param value
   *     allowed object is
   *     {@link Boolean }
   *
   */
  public void setSuspendOnOutboundInternationalRoaming(Boolean value) {
    this.suspendOnOutboundInternationalRoaming = value;
  }

  /**
   * Gets the value of the reportPostDialledDigits property.
   *
   * @return
   *     possible object is
   *     {@link Boolean }
   *
   */
  public Boolean isReportPostDialledDigits() {
    return reportPostDialledDigits;
  }

  /**
   * Sets the value of the reportPostDialledDigits property.
   *
   * @param value
   *     allowed object is
   *     {@link Boolean }
   *
   */
  public void setReportPostDialledDigits(Boolean value) {
    this.reportPostDialledDigits = value;
  }
}
