//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.etsi.uri._03221.x1._2017._10;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TaskDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaskDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="xId" type="{http://uri.etsi.org/03221/X1/2017/10}XId"/>
 *         <element name="targetIdentifiers" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfTargetIdentifiers"/>
 *         <element name="deliveryType" type="{http://uri.etsi.org/03221/X1/2017/10}DeliveryType"/>
 *         <element name="listOfDIDs" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfDids"/>
 *         <element name="listOfMediationDetails" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfMediationDetails" minOccurs="0"/>
 *         <element name="correlationID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="implicitDeactivationAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="productID" type="{http://uri.etsi.org/03221/X1/2017/10}XId" minOccurs="0"/>
 *         <element name="listOfServiceTypes" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfServiceTypes" minOccurs="0"/>
 *         <element name="taskDetailsExtensions" type="{http://uri.etsi.org/03221/X1/2017/10}TaskDetailsExtensions" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="listOfTrafficPolicyReferences" type="{http://uri.etsi.org/03221/X1/2017/10}ListOfTrafficPolicyReferences" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskDetails", propOrder = {
    "xId",
    "targetIdentifiers",
    "deliveryType",
    "listOfDIDs",
    "listOfMediationDetails",
    "correlationID",
    "implicitDeactivationAllowed",
    "productID",
    "listOfServiceTypes",
    "taskDetailsExtensions",
    "listOfTrafficPolicyReferences"
})
public class TaskDetails {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String xId;
    @XmlElement(required = true)
    protected ListOfTargetIdentifiers targetIdentifiers;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected DeliveryType deliveryType;
    @XmlElement(required = true)
    protected ListOfDids listOfDIDs;
    protected ListOfMediationDetails listOfMediationDetails;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger correlationID;
    protected Boolean implicitDeactivationAllowed;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String productID;
    protected ListOfServiceTypes listOfServiceTypes;
    protected List<TaskDetailsExtensions> taskDetailsExtensions;
    protected ListOfTrafficPolicyReferences listOfTrafficPolicyReferences;

    /**
     * Gets the value of the xId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXId() {
        return xId;
    }

    /**
     * Sets the value of the xId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXId(String value) {
        this.xId = value;
    }

    /**
     * Gets the value of the targetIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfTargetIdentifiers }
     *     
     */
    public ListOfTargetIdentifiers getTargetIdentifiers() {
        return targetIdentifiers;
    }

    /**
     * Sets the value of the targetIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfTargetIdentifiers }
     *     
     */
    public void setTargetIdentifiers(ListOfTargetIdentifiers value) {
        this.targetIdentifiers = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryType }
     *     
     */
    public DeliveryType getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryType }
     *     
     */
    public void setDeliveryType(DeliveryType value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the listOfDIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfDids }
     *     
     */
    public ListOfDids getListOfDIDs() {
        return listOfDIDs;
    }

    /**
     * Sets the value of the listOfDIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfDids }
     *     
     */
    public void setListOfDIDs(ListOfDids value) {
        this.listOfDIDs = value;
    }

    /**
     * Gets the value of the listOfMediationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfMediationDetails }
     *     
     */
    public ListOfMediationDetails getListOfMediationDetails() {
        return listOfMediationDetails;
    }

    /**
     * Sets the value of the listOfMediationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfMediationDetails }
     *     
     */
    public void setListOfMediationDetails(ListOfMediationDetails value) {
        this.listOfMediationDetails = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCorrelationID(BigInteger value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the implicitDeactivationAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImplicitDeactivationAllowed() {
        return implicitDeactivationAllowed;
    }

    /**
     * Sets the value of the implicitDeactivationAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImplicitDeactivationAllowed(Boolean value) {
        this.implicitDeactivationAllowed = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductID(String value) {
        this.productID = value;
    }

    /**
     * Gets the value of the listOfServiceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfServiceTypes }
     *     
     */
    public ListOfServiceTypes getListOfServiceTypes() {
        return listOfServiceTypes;
    }

    /**
     * Sets the value of the listOfServiceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfServiceTypes }
     *     
     */
    public void setListOfServiceTypes(ListOfServiceTypes value) {
        this.listOfServiceTypes = value;
    }

    /**
     * Gets the value of the taskDetailsExtensions property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskDetailsExtensions property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTaskDetailsExtensions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskDetailsExtensions }
     * </p>
     * 
     * 
     * @return
     *     The value of the taskDetailsExtensions property.
     */
    public List<TaskDetailsExtensions> getTaskDetailsExtensions() {
        if (taskDetailsExtensions == null) {
            taskDetailsExtensions = new ArrayList<>();
        }
        return this.taskDetailsExtensions;
    }

    /**
     * Gets the value of the listOfTrafficPolicyReferences property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfTrafficPolicyReferences }
     *     
     */
    public ListOfTrafficPolicyReferences getListOfTrafficPolicyReferences() {
        return listOfTrafficPolicyReferences;
    }

    /**
     * Sets the value of the listOfTrafficPolicyReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfTrafficPolicyReferences }
     *     
     */
    public void setListOfTrafficPolicyReferences(ListOfTrafficPolicyReferences value) {
        this.listOfTrafficPolicyReferences = value;
    }

}
