name: Verify Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "21"
          cache: maven
          server-id: central
      - name: Build and Test
        run: mvn -B clean test
